### PR TITLE
OS X support

### PR DESCRIPTION
**Pull request by nimrody**
Suggested changes to support OS X.

Note that these suggestions cannot be applied as is since:
- prologue.mk was modified to use OS X 'md5' rather than Linux' 'md5sum'. This should be automatically configured.
- qake script changed to use locally installed gmake 4.0. This should depend on whether we chose to install it. Otherwise, continue using the system default.

### CODE REVIEW

**Comment by mkpankov** [comment]
Do you think you'll be able to finish this one on your own?

**Comment by nimrody** [comment]
Regarding `.make_path` -- Seems like it is created in the directory where the install script is executed. Should instead create it explicitly at `$QAKE_INCLUDE_DIR` and source it from there.

(I'll take care of the HASH myself and update the pull request)

**Comment by mkpankov** [comment]
Ok, thanks!

**Comment by nimrody** [comment]
Should be OK now. Automatically selects `md5` if `md5sum` is not available and correctly uses `.make_path` to use the newly installed gnu make 4.0

**Pull request merged**
